In [1]:
import numpy as np

### Ways of creating array

In [2]:
# first way of creating array
x1 = np.array([3,4,2,5,6,12,34,67,7])

In [3]:
x1

array([ 3,  4,  2,  5,  6, 12, 34, 67,  7])

In [4]:
x1 = np.array([[3,4,2],[5,6,12],[34,67,7]])
x1

array([[ 3,  4,  2],
       [ 5,  6, 12],
       [34, 67,  7]])

In [5]:
# 2nd way of creating array
x2 = np.arange(1,10)
x2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
x2 = np.arange(1,21,2)
x2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [8]:
# 3rd way of creating array
# linspace - linear space
# will create an array with 50 elements b/w 1 to 10 with equal interval/gap
x3 = np.linspace(1,10)
x3

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [10]:
# retstep - return step
x3 = np.linspace(1,10,num=25,retstep=True)
x3

(array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
         4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
         7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
        10.   ]),
 0.375)

In [11]:
# 4th way of creating array
x4 = np.zeros(5)
x4

array([0., 0., 0., 0., 0.])

In [14]:
x4 = np.zeros((4,5),dtype='int')
x4

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
x4 + 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
# 5th way of creating array
x5 = np.ones(5)
x5

array([1., 1., 1., 1., 1.])

In [16]:
x5 = np.ones((5,6))
x5

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
# 6th way of creating array
x6 = np.identity(5)
x6

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# 7th way of creating array
x7 = np.zeros_like(x1)
x7

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
# 8th way of creating array
# will return a number b/w 0 to 1
np.random.random()

0.9291211871504291

In [20]:
np.random.random(4)

array([0.27718433, 0.56680328, 0.86729862, 0.41713951])

In [21]:
np.random.random((4,4))

array([[0.61295845, 0.82230523, 0.48406336, 0.58985089],
       [0.75049141, 0.68839866, 0.30103789, 0.00381046],
       [0.55308402, 0.38499828, 0.53074752, 0.18397682],
       [0.24328334, 0.51279476, 0.26110177, 0.33473761]])

In [27]:
np.random.randn(5)

array([ 0.4316017 , -0.12537793, -1.65581493,  0.27275785, -0.02583296])

In [29]:
np.random.randn(5,5)

array([[ 0.36283533, -0.36847248,  1.74197133,  0.2521112 , -0.97821402],
       [ 0.34469737, -0.17806556, -2.16845263,  0.4598189 ,  0.24904976],
       [ 0.84992179, -0.36239599,  0.16982938,  2.08500817,  0.72142196],
       [ 1.14111341,  0.3758856 ,  0.38402475,  0.16928896, -1.72662405],
       [-0.51360014,  0.77943959,  0.00609762,  1.16706536,  0.53234731]])

In [30]:
np.random.randint(1,10)

3

In [31]:
np.random.randint(1,10,5)

array([3, 7, 7, 5, 3])

In [32]:
np.random.randint(1,50,(5,5))

array([[ 3, 36, 12, 18, 19],
       [32,  9, 14, 34, 12],
       [ 7,  4, 45,  7, 10],
       [34, 43, 14, 12,  2],
       [19, 44, 14, 32, 23]])

### Slicing Numpy Array

In [35]:
x = np.random.randint(1,50,5)

In [36]:
x

array([12, 26, 35, 14, 24])

In [37]:
x[0]

12

In [38]:
x[0:3]

array([12, 26, 35])

In [39]:
x[-1]

24

In [40]:
x = np.random.randint(1,50,(5,5))

In [41]:
x

array([[11, 37, 31, 45, 16],
       [ 2, 12, 15,  3, 16],
       [26, 29, 25, 39,  8],
       [17, 38, 47, 20, 23],
       [32,  9,  5,  8, 18]])

In [42]:
x[0]

array([11, 37, 31, 45, 16])

In [43]:
x[1]

array([ 2, 12, 15,  3, 16])

In [44]:
x[0:3]

array([[11, 37, 31, 45, 16],
       [ 2, 12, 15,  3, 16],
       [26, 29, 25, 39,  8]])

In [45]:
x[0][0]

11

In [47]:
x[0:3,0]

array([11,  2, 26])

In [48]:
x[0:3,0:3]

array([[11, 37, 31],
       [ 2, 12, 15],
       [26, 29, 25]])

In [49]:
x[:,0]

array([11,  2, 26, 17, 32])

In [50]:
x[:,0:1]

array([[11],
       [ 2],
       [26],
       [17],
       [32]])

In [51]:
x[:,0:2]

array([[11, 37],
       [ 2, 12],
       [26, 29],
       [17, 38],
       [32,  9]])

In [52]:
x[1:4,1:4]

array([[12, 15,  3],
       [29, 25, 39],
       [38, 47, 20]])

In [53]:
np.random.random((3,3,3))

array([[[0.82759771, 0.92677179, 0.33645098],
        [0.08737479, 0.48359499, 0.41950393],
        [0.75442105, 0.2331939 , 0.85998372]],

       [[0.6206859 , 0.4643646 , 0.32352114],
        [0.68787847, 0.37437386, 0.57284222],
        [0.77599316, 0.99531173, 0.36057001]],

       [[0.73065668, 0.19085636, 0.47332736],
        [0.74024104, 0.87558556, 0.72165447],
        [0.28202157, 0.57804838, 0.91643206]]])

### Numpy Methods 

In [54]:
x

array([[11, 37, 31, 45, 16],
       [ 2, 12, 15,  3, 16],
       [26, 29, 25, 39,  8],
       [17, 38, 47, 20, 23],
       [32,  9,  5,  8, 18]])

In [55]:
x.shape

(5, 5)

In [56]:
x.ndim

2

In [57]:
# will convert array to 1D
x.flatten()

array([11, 37, 31, 45, 16,  2, 12, 15,  3, 16, 26, 29, 25, 39,  8, 17, 38,
       47, 20, 23, 32,  9,  5,  8, 18])

In [58]:
x = np.random.randint(1,50,(4,6))

In [59]:
x

array([[24, 16, 23, 19, 42, 36],
       [46, 31, 15, 45, 23, 19],
       [18, 39, 16, 24,  7, 16],
       [45,  9, 12, 36, 34, 36]])

In [60]:
x.flatten()

array([24, 16, 23, 19, 42, 36, 46, 31, 15, 45, 23, 19, 18, 39, 16, 24,  7,
       16, 45,  9, 12, 36, 34, 36])

In [61]:
x.shape

(4, 6)

In [62]:
x.reshape((6,4))

array([[24, 16, 23, 19],
       [42, 36, 46, 31],
       [15, 45, 23, 19],
       [18, 39, 16, 24],
       [ 7, 16, 45,  9],
       [12, 36, 34, 36]])

In [64]:
x.reshape((2,12))

array([[24, 16, 23, 19, 42, 36, 46, 31, 15, 45, 23, 19],
       [18, 39, 16, 24,  7, 16, 45,  9, 12, 36, 34, 36]])

In [65]:
x.reshape((3,8))

array([[24, 16, 23, 19, 42, 36, 46, 31],
       [15, 45, 23, 19, 18, 39, 16, 24],
       [ 7, 16, 45,  9, 12, 36, 34, 36]])

In [66]:
x.reshape((4,-1))

array([[24, 16, 23, 19, 42, 36],
       [46, 31, 15, 45, 23, 19],
       [18, 39, 16, 24,  7, 16],
       [45,  9, 12, 36, 34, 36]])

In [67]:
x.reshape((-1,6))

array([[24, 16, 23, 19, 42, 36],
       [46, 31, 15, 45, 23, 19],
       [18, 39, 16, 24,  7, 16],
       [45,  9, 12, 36, 34, 36]])

In [68]:
x1 = x.flatten()

In [69]:
x1

array([24, 16, 23, 19, 42, 36, 46, 31, 15, 45, 23, 19, 18, 39, 16, 24,  7,
       16, 45,  9, 12, 36, 34, 36])

In [70]:
np.min(x1)

7

In [71]:
np.max(x1)

46

In [72]:
np.argmin(x1)

16

In [73]:
np.argmax(x1)

6

In [74]:
np.sort(x1)

array([ 7,  9, 12, 15, 16, 16, 16, 18, 19, 19, 23, 23, 24, 24, 31, 34, 36,
       36, 36, 39, 42, 45, 45, 46])

In [75]:
np.argsort(x1)

array([16, 19, 20,  8,  1, 17, 14, 12, 11,  3,  2, 10, 15,  0,  7, 22,  5,
       21, 23, 13,  4,  9, 18,  6], dtype=int64)

In [76]:
np.mean(x1)

26.291666666666668

In [77]:
np.median(x1)

23.5

In [78]:
np.std(x1)

11.883038215129254

In [80]:
x

array([[24, 16, 23, 19, 42, 36],
       [46, 31, 15, 45, 23, 19],
       [18, 39, 16, 24,  7, 16],
       [45,  9, 12, 36, 34, 36]])

In [79]:
np.min(x)

7

In [81]:
# will return minimum value of each column
np.min(x, axis=0)

array([18,  9, 12, 19,  7, 16])

In [82]:
# will return minimum value of each row
np.min(x, axis=1)

array([16, 15,  7,  9])

In [83]:
np.max(x, axis=0)

array([46, 39, 23, 45, 42, 36])

In [84]:
np.mean(x, axis=1)

array([26.66666667, 29.83333333, 20.        , 28.66666667])

In [85]:
np.mean(x, axis=0)

array([33.25, 23.75, 16.5 , 31.  , 26.5 , 26.75])

In [86]:
x

array([[24, 16, 23, 19, 42, 36],
       [46, 31, 15, 45, 23, 19],
       [18, 39, 16, 24,  7, 16],
       [45,  9, 12, 36, 34, 36]])

In [88]:
col_1 = np.array([[3],[2],[4],[5]])
np.c_[x,col_1]

array([[24, 16, 23, 19, 42, 36,  3],
       [46, 31, 15, 45, 23, 19,  2],
       [18, 39, 16, 24,  7, 16,  4],
       [45,  9, 12, 36, 34, 36,  5]])

In [91]:
row_1 = np.array([[8,7,3,2,4,5]])
np.r_[x,row_1]

array([[24, 16, 23, 19, 42, 36],
       [46, 31, 15, 45, 23, 19],
       [18, 39, 16, 24,  7, 16],
       [45,  9, 12, 36, 34, 36],
       [ 8,  7,  3,  2,  4,  5]])