In [30]:
import numpy as np
import random
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, OneHotEncoder
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [37]:
df = pd.read_csv('Churn_Modelling.csv')

In [38]:
df.shape

(10000, 14)

In [39]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [40]:
label = LabelEncoder()
df['Gender'] = label.fit_transform(df['Gender'])

In [41]:
# df.head()

In [42]:
df['Geography'] = label.fit_transform(df['Geography'])

In [43]:
df.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          608          2       0   41   
2          3    15619304      Onio          502          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [44]:
geog = df['Geography'].values

In [45]:
onehot = OneHotEncoder()
geog = onehot.fit_transform(geog.reshape(-1,1))

In [46]:
geog

<10000x3 sparse matrix of type '<class 'numpy.float64'>'
	with 10000 stored elements in Compressed Sparse Row format>

In [47]:
geog = geog.toarray()

In [48]:
geog

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [49]:
del df['Geography']

In [56]:
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values

In [57]:
X = np.c_[X,geog]

In [58]:
X.shape

(10000, 12)

In [59]:
minmax = MinMaxScaler()
X = minmax.fit_transform(X)

In [60]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [61]:
X[0]

array([0.538     , 0.        , 0.32432432, 0.2       , 0.        ,
       0.        , 1.        , 1.        , 0.50673489, 1.        ,
       0.        , 0.        ])

In [62]:
cross_validation = KFold(n_splits=5)

In [63]:
cross_validation.get_n_splits(X)

5

In [68]:
for train_index, test_index in cross_validation.split(X):
    print(train_index, test_index)
    x_train, x_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

[2000 2001 2002 ... 9997 9998 9999] [   0    1    2 ... 1997 1998 1999]
[   0    1    2 ... 9997 9998 9999] [2000 2001 2002 ... 3997 3998 3999]
[   0    1    2 ... 9997 9998 9999] [4000 4001 4002 ... 5997 5998 5999]
[   0    1    2 ... 9997 9998 9999] [6000 6001 6002 ... 7997 7998 7999]
[   0    1    2 ... 7997 7998 7999] [8000 8001 8002 ... 9997 9998 9999]


In [65]:
x_train.shape

(8000, 12)

In [66]:
x_test.shape

(2000, 12)

In [67]:
y_train.shape

(8000,)

In [70]:
for train_index, test_index in cross_validation.split(X):
#     print(train_index, test_index)
    x_train, x_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    
    logistic = LogisticRegression()
    logistic.fit(x_train, y_train)
    
    y_pred = logistic.predict(x_test)
    
    acc = accuracy_score(y_test, y_pred)
    print("Accuracy :",acc)

Accuracy : 0.8085
Accuracy : 0.8025
Accuracy : 0.8085
Accuracy : 0.825
Accuracy : 0.807
